### ISSUE TITLE
页面上传失败

### ISSUE THREAD

**Issue by EWEDLCM** [MarSeventh/CloudFlare-ImgBed#103]
按照教程，采用cloudfalre方案，当3.1.2.1部署于Cloudflare 整个步骤结束后进行重新构建，此时进入网页可以正常打开，但上传图片时提示上传失败

**Comment by MarSeventh** [comment]
麻烦F12看看上传接口的响应内容

**Comment by EWEDLCM** [comment]
感谢你的恢复，刚刚排查发现变量多打了个符号，导致无法正常上传。目前问题已解决！
