### ISSUE TITLE
希望能多增加一个变量，使得可以单独使用R2存储

### ISSUE THREAD

**Issue by billy74** [MarSeventh/CloudFlare-ImgBed#108]
# 问题描述
> 建议出问题先更新到最新版本，查看已有issue；请在labels设置中加上问题类型
希望能多增加一个变量，使得可以单独使用R2存储。
目前是必须要有TG才能使用这个项目，能否增加一个变量判断使得可以单独使用R2作为存储端来上传图片。

# 上传渠道
> Telegram, Cloudflare R2等
建议可选单独使用Cloudflare R2，毕竟TG使用起来还需要其他方法
后期如果可以在后台进行选择后端存储就好了，如果可以对接S3协议就更完美了

**Comment by MarSeventh** [comment]
不配置TG，只使用R2也是可以上传的。
web端在上传设置中选择R2，API端设置上传url参数就可以了。

**Comment by billy74** [comment]
已解决
