### ISSUE TITLE
设置了AUTH_CODE留空也可以进入页面上传图片

### ISSUE THREAD

**Issue by Jisucloud** [MarSeventh/CloudFlare-ImgBed#11]
设置了AUTH_CODE变量，web页面留空也可以直接进入页面上传图片

**Comment by MarSeventh** [comment]
重新部署了吗

**Comment by Jisucloud** [comment]
重新部署了

**Comment by MarSeventh** [comment]
能否用无痕模式试一下。
我这边无法复现该问题，留空认证码上传会直接提示认证状态错误。
同时请展示一下cf中环境变量的设置截图。

**Comment by Sagit666** [comment]
> 能否用无痕模式试一下。 我这边无法复现该问题，留空认证码上传会直接提示认证状态错误。 同时请展示一下cf中环境变量的设置截图。

我刚想说我也遇到这个问题，想着用刚部署好的图床截图传上来，结果发现上传页面密码留空直接点“Submit”是可以拖图进行上传，而它是要等上传到最后才会跳出提示“认证状态错误”，能否优化成 密码认证不通过无法跳转到上传界面呢？这样就不会给人一种不认证似乎也能上传图的错觉了。

**Comment by MarSeventh** [comment]
> > 能否用无痕模式试一下。 我这边无法复现该问题，留空认证码上传会直接提示认证状态错误。 同时请展示一下cf中环境变量的设置截图。
> 
> 我刚想说我也遇到这个问题，想着用刚部署好的图床截图传上来，结果发现上传页面密码留空直接点“Submit”是可以拖图进行上传，而它是要等上传到最后才会跳出提示“认证状态错误”，能否优化成 密码认证不通过无法跳转到上传界面呢？这样就不会给人一种不认证似乎也能上传图的错觉了。

这个也是无奈之举，本着对原项目后端改动最小的理念设计的执行逻辑。我下来继续完善一下后端，尽量让前端操作更加符合直觉。

**Comment by Sagit666** [comment]
> > > 能否用无痕模式试一下。 我这边无法复现该问题，留空认证码上传会直接提示认证状态错误。 同时请展示一下cf中环境变量的设置截图。
> > 
> > 
> > 我刚想说我也遇到这个问题，想着用刚部署好的图床截图传上来，结果发现上传页面密码留空直接点“Submit”是可以拖图进行上传，而它是要等上传到最后才会跳出提示“认证状态错误”，能否优化成 密码认证不通过无法跳转到上传界面呢？这样就不会给人一种不认证似乎也能上传图的错觉了。
> 
> 这个也是无奈之举，本着对原项目后端改动最小的理念设计的执行逻辑。我下来继续完善一下后端，尽量让前端操作更加符合直觉。

救命，刚准备用，结果传了3个图片，图片全部自动变成404这是什么情况呀？

**Comment by MarSeventh** [comment]
> > > > 能否用无痕模式试一下。 我这边无法复现该问题，留空认证码上传会直接提示认证状态错误。 同时请展示一下cf中环境变量的设置截图。
> > > 
> > > 
> > > 我刚想说我也遇到这个问题，想着用刚部署好的图床截图传上来，结果发现上传页面密码留空直接点“Submit”是可以拖图进行上传，而它是要等上传到最后才会跳出提示“认证状态错误”，能否优化成 密码认证不通过无法跳转到上传界面呢？这样就不会给人一种不认证似乎也能上传图的错觉了。
> > 
> > 这个也是无奈之举，本着对原项目后端改动最小的理念设计的执行逻辑。我下来继续完善一下后端，尽量让前端操作更加符合直觉。
> 
> 救命，刚准备用，结果传了3个图片，图片全部自动变成404这是什么情况呀？

上传所有图片都这样吗？出现404图片是因为预览图无法打开。
可以给我看一下上传页面的情况。

**Comment by Sagit666** [comment]
> > > > > 能否用无痕模式试一下。 我这边无法复现该问题，留空认证码上传会直接提示认证状态错误。 同时请展示一下cf中环境变量的设置截图。
> > > > 
> > > > 
> > > > 我刚想说我也遇到这个问题，想着用刚部署好的图床截图传上来，结果发现上传页面密码留空直接点“Submit”是可以拖图进行上传，而它是要等上传到最后才会跳出提示“认证状态错误”，能否优化成 密码认证不通过无法跳转到上传界面呢？这样就不会给人一种不认证似乎也能上传图的错觉了。
> > > 
> > > 
> > > 这个也是无奈之举，本着对原项目后端改动最小的理念设计的执行逻辑。我下来继续完善一下后端，尽量让前端操作更加符合直觉。
> > 
> > 
> > 救命，刚准备用，结果传了3个图片，图片全部自动变成404这是什么情况呀？
> 
> 上传所有图片都这样吗？出现404图片是因为预览图无法打开。 可以给我看一下上传页面的情况。

谢谢你的回复，后来我直接删了重新部署了，有了之前的经验，只花几分钟就重新部署完成并正常使用了。

**Comment by MarSeventh** [comment]
> > 能否用无痕模式试一下。 我这边无法复现该问题，留空认证码上传会直接提示认证状态错误。 同时请展示一下cf中环境变量的设置截图。
> 
> 我刚想说我也遇到这个问题，想着用刚部署好的图床截图传上来，结果发现上传页面密码留空直接点“Submit”是可以拖图进行上传，而它是要等上传到最后才会跳出提示“认证状态错误”，能否优化成 密码认证不通过无法跳转到上传界面呢？这样就不会给人一种不认证似乎也能上传图的错觉了。

最新版本已完善登录认证方式，密码错误无法进入上传页面。
