### ISSUE TITLE
添加代理缓存加速

### ISSUE THREAD

**Issue by zy111x** [MarSeventh/CloudFlare-ImgBed#110]
# 功能需求
> 尽可能详细描述您的需求
大佬你好，之前看过一个图床，虽然不在服务器上部署很慢，但是可以添加代理缓存进行加速，比如i1.wp.com,然后我就想有没有可能在这个项目也添加代理缓存加速呢。
下面这是那个图床地项目，这个开发者用的是php,我不了解这个，你看有没有可能添加这一需求
https://github.com/JLinMr/PixPro/
这个图床项目好像添加了i1.wp.com作为代理缓存，这样速度更快了
https://i1.wp.com/dev.ruom.top/i/2024/10/14/514926.webp

**Comment by zy111x** [comment]
https://github.com/x-dr/telegraph-Image
这个是我之前用的tg图床项目，有一个自定义加速域名服务。但是这个容易失效，大佬你这个图床项目不会失效，我就想希望能不能也加一个加速域名服务

**Comment by MarSeventh** [comment]
有计划支持自定义前缀，你看看是否和你这个需求吻合呢

**Comment by zy111x** [comment]
> 有计划支持自定义前缀，你看看是否和你这个需求吻合呢
吻合吻合，自定义前缀完全🆗，辛苦大佬

**Comment by MarSeventh** [comment]
新版本已至此自定义前缀，请在上传页面，链接设置处进行设置。
