### ISSUE TITLE
给尊重的开发者的建议——开放更多文件格式

### ISSUE THREAD

**Issue by Renjiu13** [MarSeventh/CloudFlare-ImgBed#111]
开放更多文件格式，可以让其发挥更多的作用。
例如：
- 博客小文件分享
- 备份小而不是很重要，但可能用上的文件

不单单可以最为一个图床系统，更是一个小网盘系统，看打出来他的潜力。
我非常看好作者大大。

**Comment by MarSeventh** [comment]
感谢建议！
目前拖拽上传不限制文件格式，可以存储文件使用。
后面也会对其他文件格式加强适配，不再局限于图床功能。
