### ISSUE TITLE
后台只能记录1000个吗？

### ISSUE THREAD

**Issue by wunskzb** [MarSeventh/CloudFlare-ImgBed#12]
[https://img.898965.xyz/file/402ccb5958090c2d07c58.png](url)
[https://img.898965.xyz/file/74d4e07e10b06c002e9c2.png](url)
难道是KV限制了么？但是正常来说到达使用量了
赛博菩萨不会禁止的啊

**Comment by MarSeventh** [comment]
我这边可以打开这两张图，后台记录数量不限制，限制的是每天读取、列出和写入的次数。
