### ISSUE TITLE
Feature Request: dashboard批量选择时支持记录用户选择的顺序

### ISSUE THREAD

**Issue by Hyphen-H** [MarSeventh/CloudFlare-ImgBed#124]
# 场景复现
很多时候我都是批量上传图片（10-20张），这些图片上传之后在图床中常常是乱序的；
整理到笔记软件时，需要按照顺序排列（如时间顺序/逻辑顺序等等），希望导入到笔记软件的imgurl可以拥有我精心选择的顺序；
于是我到dashboard按顺序多选图片，批量复制链接。。。 
经测试，当前的版本不会按照 `用户选择图片的先后顺序` 来排列即将导入到剪切板中的`批量图片链接` 的顺序。

# 期待实现的Feature
就像手机相册选择图片发给别人一样，可以记录选择的顺序（比如给朋友按时间顺序分享旅行见闻等）依次选中复选框后，图片上的复选框记录选择的顺序，变为1,2,3,4，依此类推
这样图片就会在批量选择的时候排好序

**Comment by MarSeventh** [comment]
新版本已经加入该特性
