### ISSUE TITLE
大佬，web端Telegram渠道只能上传5mb以内的图片吗

### ISSUE THREAD

**Issue by icelion588** [MarSeventh/CloudFlare-ImgBed#127]
# 问题描述
> 通过服务器搭建的web端，可以正常上传图片，但是图片超过5mb就上传不了了，请问这个是我的配置有问题吗

# 上传方式
> web 

# 上传渠道
> Telegram

**Comment by MarSeventh** [comment]
不会呀，前端正常是带带压缩的，而且限制也是20MB，是不是你服务器对请求包大小有限制

**Comment by icelion588** [comment]
> 不会呀，前端正常是带压缩的，而且限制也是20MB，是不是你服务器对请求包大小有限制

弄好了，谢谢大佬
