### ISSUE TITLE
关于api返回链接不完整问题

### ISSUE THREAD

**Issue by EVAyo** [MarSeventh/CloudFlare-ImgBed#128]
# 功能需求
> 尽可能详细描述您的需求

api部分是否可以通过读请求体host或者额外的请求头字段传输域名来返回完整的图片链接

# 应用场景
api

# 可行方案
> 您对该功能的实现有哪些想法

**Comment by MarSeventh** [comment]
新版本已支持返回完整链接，请查看API文档，设置`returnFormat`参数
