### ISSUE TITLE
好像不支持webp图片上传

### ISSUE THREAD

**Issue by leaflyingl** [MarSeventh/CloudFlare-ImgBed#13]
请问可以解决吗？

**Comment by leaflyingl** [comment]
后台链接格式只有一种，能改成添加页面一样的多格式吗？

**Comment by it985** [comment]
支持，但是上传后转jpg了
https://demo-cloudflare-imgbed.pages.dev/file/a50385d4eac360ad26102.jpg  这个就是我本地webp上传后转的

**Comment by MarSeventh** [comment]
> 后台链接格式只有一种，能改成添加页面一样的多格式吗？

后面有计划修改后台页面，到时候会完善相关功能。

**Comment by leaflyingl** [comment]
> 支持，但是上传后转jpg了 https://demo-cloudflare-imgbed.pages.dev/file/a50385d4eac360ad26102.jpg 这个就是我本地webp上传后转的

不知道为啥我这里有问题，webp就是上不去

<img width="347" alt="1723564680554" src="https://github.com/user-attachments/assets/33677443-4414-4e7e-a165-de7c2df8441a">

**Comment by MarSeventh** [comment]
> > 支持，但是上传后转jpg了 https://demo-cloudflare-imgbed.pages.dev/file/a50385d4eac360ad26102.jpg 这个就是我本地webp上传后转的
> 
> 不知道为啥我这里有问题，webp就是上不去
> 
> <img width="347" alt="1723564680554" src="https://github.com/user-attachments/assets/33677443-4414-4e7e-a165-de7c2df8441a">
> 

可以换另一张webp试试，因为telegraph的API会在后台进行图片校验，部分图片无法上传。

**Comment by leaflyingl** [comment]
> > > 支持，但是上传后转jpg了 https://demo-cloudflare-imgbed.pages.dev/file/a50385d4eac360ad26102.jpg 这个就是我本地webp上传后转的
> > 
> > 
> > 不知道为啥我这里有问题，webp就是上不去
> > <img alt="1723564680554" width="347" src="https://private-user-images.githubusercontent.com/174892524/357483045-33677443-4414-4e7e-a165-de7c2df8441a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NjUxMTksIm5iZiI6MTcyMzU2NDgxOSwicGF0aCI6Ii8xNzQ4OTI1MjQvMzU3NDgzMDQ1LTMzNjc3NDQzLTQ0MTQtNGU3ZS1hMTY1LWRlN2MyZGY4NDQxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxNjAwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2ZiODE5MjI1ZjM1ODdmY2ViN2YxNDgzZWZiNjI2YjYzMzhkNjQ1ZTk4OGFhYThjZjc1MWUzYmZlYzI3ZGE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D-tapqe0ncBk4g7P96tUMi913rehWodKWXmsbkW75dI">
> 
> 可以换另一张webp试试，因为telegraph的API会在后台进行图片校验，部分图片无法上传。

试了好几张不同内容的webp都不能上传。。。格式 大小 没为题，内容 也应该是没啥问题。。。

**Comment by MarSeventh** [comment]
看了下telegraph支持上传的文件类型，不支持webp格式。
![image](https://github.com/user-attachments/assets/3791fe10-0a05-4f50-8538-0cfc04b60e34)

**Comment by leaflyingl** [comment]
> 看了下telegraph支持上传的文件类型，不支持webp格式。 ![image](https://private-user-images.githubusercontent.com/108160987/358982368-3791fe10-0a05-4f50-8538-0cfc04b60e34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMzIyNjIsIm5iZiI6MTcyNDEzMTk2MiwicGF0aCI6Ii8xMDgxNjA5ODcvMzU4OTgyMzY4LTM3OTFmZTEwLTBhMDUtNGY1MC04NTM4LTBjZmMwNGI2MGUzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQwNTMyNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDYyY2RkMjE2MDU0ZWEyNjc3MjNiYzA4MjUwYWFkMTEyNWQ0ODUxZDNmMjIyNmY0OWE1Mjc2MDUxN2Q1MTJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D6qbANDBWnhoFnSviRk2ZO1J0Tt5LjU2r4W4fv5TpKI)

谢谢！
