### ISSUE TITLE
能不能自动显示HTML和Markdown的插入代码

### ISSUE THREAD

**Issue by bestZwei** [MarSeventh/CloudFlare-ImgBed#15]
如题

**Comment by MarSeventh** [comment]
需要展示在哪里呢

**Comment by bestZwei** [comment]
增加一个显示框，显示三个链接，类似 https://pics.sputnik.cloudns.ch/

**Comment by MarSeventh** [comment]
> 增加一个显示框，显示三个链接，类似 https://pics.sputnik.cloudns.ch/

可以，后续版本加上

**Comment by sucooer** [comment]
> > 增加一个显示框，显示三个链接，类似 https://pics.sputnik.cloudns.ch/
> 
> 可以，后续版本加上

希望增加`ubb`格式

**Comment by ywgx** [comment]
```
目前是这样 <img src="https://img.xabc.io/file/45b300bef34497af15f78.jpg" alt="GVP4XaobsAA2zh8.jpeg">

其实这样更合适 <img src="https://img.xabc.io/file/45b300bef34497af15f78.jpg" width=100%>
```

**Comment by MarSeventh** [comment]
> ```
> 目前是这样 <img src="https://img.xabc.io/file/45b300bef34497af15f78.jpg" alt="GVP4XaobsAA2zh8.jpeg">
> 
> 其实这样更合适 <img src="https://img.xabc.io/file/45b300bef34497af15f78.jpg" width=100%>
> ```

好的，感谢提醒。

**Comment by MarSeventh** [comment]
最新版本已增加UBB格式，并直接展示四种格式链接。

**Comment by sucooer** [comment]
> 最新版本已增加UBB格式，并直接展示四种格式链接。

更新后点了下注销彻底进不去主页面了，原本没有设置`AUTH_CODE`的，环境变量添加了AUTH_CODE重新部署还是进不去![IMG_20240822_225922.jpg](https://github.com/user-attachments/assets/084f18f0-44af-40e3-b505-1b9f68b0a3ae)

**Comment by MarSeventh** [comment]
> > 最新版本已增加UBB格式，并直接展示四种格式链接。
> 
> 更新后点了下注销彻底进不去主页面了，原本没有设置`AUTH_CODE`的，环境变量添加了AUTH_CODE重新部署还是进不去![IMG_20240822_225922.jpg](https://github.com/user-attachments/assets/084f18f0-44af-40e3-b505-1b9f68b0a3ae)
> 
> 

用电脑无痕模式试试呢？我这边有没有authcode都是测试过的，应该没问题。

**Comment by MarSeventh** [comment]
> > 最新版本已增加UBB格式，并直接展示四种格式链接。
> 
> 更新后点了下注销彻底进不去主页面了，原本没有设置`AUTH_CODE`的，环境变量添加了AUTH_CODE重新部署还是进不去![IMG_20240822_225922.jpg](https://github.com/user-attachments/assets/084f18f0-44af-40e3-b505-1b9f68b0a3ae)
> 
> 

演示站即未设置authcode的情况。

**Comment by sucooer** [comment]
> > > 最新版本已增加UBB格式，并直接展示四种格式链接。
> > 
> > 更新后点了下注销彻底进不去主页面了，原本没有设置`AUTH_CODE`的，环境变量添加了AUTH_CODE重新部署还是进不去![IMG_20240822_225922.jpg](https://github.com/user-attachments/assets/084f18f0-44af-40e3-b505-1b9f68b0a3ae)
> > 
> > 
> 
> 演示站即未设置authcode的情况。

我是用[Sanyue-ImgHub](https://github.com/MarSeventh/Sanyue-ImgHub)打包部署在原项目上的，开无痕清缓存问题还是存在，我又重新打包部署了一遍还是进不去。用这个项目却是没问题的

**Comment by MarSeventh** [comment]
> > > > 最新版本已增加UBB格式，并直接展示四种格式链接。
> > > 
> > > 更新后点了下注销彻底进不去主页面了，原本没有设置`AUTH_CODE`的，环境变量添加了AUTH_CODE重新部署还是进不去![IMG_20240822_225922.jpg](https://github.com/user-attachments/assets/084f18f0-44af-40e3-b505-1b9f68b0a3ae)
> > > 
> > > 
> > 
> > 演示站即未设置authcode的情况。
> 
> 我是用[Sanyue-ImgHub](https://github.com/MarSeventh/Sanyue-ImgHub)打包部署在原项目上的，开无痕清缓存问题还是存在，我又重新打包部署了一遍还是进不去。用这个项目却是没问题的

后端也有更新，记得同步更新哦。（functions目录
