### ISSUE TITLE
请教大佬怎么更换壁纸？

### ISSUE THREAD

**Issue by imyaer** [MarSeventh/CloudFlare-ImgBed#17]
我是小白，喜欢自己折腾，请教一下大佬在哪可以更换背景图片？我找了几个位置改了都不管用
/css/859.b5b65b7d.cs
/css/709.794738b3.cs
/css/729.99383612.css
/css/975.5af60a54.css
由衷感谢

**Comment by imyaer** [comment]
或者将我的背景使用图床里面一张固定的照片，非常感谢大佬

**Comment by MarSeventh** [comment]
目前来说只有改源码是正解，如果改打包好的代码可能需要修改很多地方（尝试全局替换）。
下来我看能否用更简单的办法解决。

**Comment by imyaer** [comment]
感谢大佬无私奉献~

**Comment by xfxx2022** [comment]
可以改成和之前一样的bing壁纸嘛

**Comment by MarSeventh** [comment]
> 可以改成和之前一样的bing壁纸嘛
> 

现在只能自己改代码，后面我加上接口之后可以直接更换。

**Comment by MarSeventh** [comment]
现已支持自定义壁纸轮播，同时支持bing壁纸轮播，参见最新文档。 @xfxx2022 @imyaer

**Comment by imyaer** [comment]
@MarSeventh  感谢感谢，详细看了您的文档，不知道自己理解对不对，先同步您的项目，然后在自己github这里点击设置，Environment variables里面按照要求增加变量对吗？

**Comment by MarSeventh** [comment]
> @MarSeventh  感谢感谢，详细看了您的文档，不知道自己理解对不对，先同步您的项目，然后在自己github这里点击设置，Environment variables里面按照要求增加变量对吗？

是在cloudflare对应项目处修改环境变量

**Comment by imyaer** [comment]
成功啦，棒~

**Comment by MarSeventh** [comment]
> > > @MarSeventh  感谢感谢，详细看了您的文档，不知道自己理解对不对，先同步您的项目，然后在自己github这里点击设置，Environment variables里面按照要求增加变量对吗？
> > 
> > 是在cloudflare对应项目处修改环境变量
> 
> 是我这环境变量写错了吗？重试部署后没有背景壁纸
> ![](https://img.520717.xyz/file/69858a5c53ba79c6e9532.png)

你可以直接复制我的样例再修改

**Comment by imyaer** [comment]
> > > @MarSeventh  谢谢，详细看了你的文档，不知道自己理解对不对，先同步你的项目，然后在自己github这里点击设置，环境变量里面按照要求增加变量对吗？
> > 
> > 
> > 是在cloudflare响应项目处修改环境变量
> 
> 我这个环境指标写错了吗？没有后台背景后重新试装 ![](https://camo.githubusercontent.com/34b6191ce531c5227666b0c96b61696abe1138220345c65b3ff451f96eae1530/68747470733a2f2f696d672e3532303731372e78797a2f66696c652f3639383538613563353362613739633665393533322e706e67)

你好好看看大佬的文档，操作完得重新部署一边

**Comment by sucooer** [comment]
> > > > @MarSeventh  谢谢，详细看了你的文档，不知道自己理解对不对，先同步你的项目，然后在自己github这里点击设置，环境变量里面按照要求增加变量对吗？
> > > 
> > > 
> > > 是在cloudflare响应项目处修改环境变量
> > 
> > 我这个环境指标写错了吗？没有后台背景后重新试装 ![](https://camo.githubusercontent.com/34b6191ce531c5227666b0c96b61696abe1138220345c65b3ff451f96eae1530/68747470733a2f2f696d672e3532303731372e78797a2f66696c652f3639383538613563353362613739633665393533322e706e67)
> 
> 你好好看看大佬的文档，操作完得重新部署一边

然而只是缓存的原因😶
