### ISSUE TITLE
佬 我这里已经和你同步了，为啥重新部署后还是没改变

### ISSUE THREAD

**Issue by elfcute** [MarSeventh/CloudFlare-ImgBed#20]
![image](https://github.com/user-attachments/assets/4c264748-3728-4b80-a7a5-95c83fcbd3af)
github这里已经设置同步，然后cf上面也重新部署了，但是还是没有改变https://img.oxxo.us.kg/

是啥原因，难道说我github没有真正的自动同步你的项目吗？那要咋同步你的项目

**Comment by MarSeventh** [comment]
正常来讲只需要github同步上游仓库就可以了，这种情况可能是因为你之前做了修改，同步不成功，试试重新fork一次？

**Comment by elfcute** [comment]
> 正常来讲只需要github同步上游仓库就可以了，这种情况可能是因为你之前做了修改，同步不成功，试试重新fork一次？

删除项目重新fork了一下就可以了，不过这样是不是太麻烦了，点了sync fork无法自动同步每次都要删除重新fork吗？

**Comment by MarSeventh** [comment]
不用，你这个应该是修改冲突了，正常情况sync fork就可以更新
