### ISSUE TITLE
Picgo上传失败

### ISSUE THREAD

**Issue by soslane** [MarSeventh/CloudFlare-ImgBed#23]
![image](https://github.com/user-attachments/assets/f2b13a23-b192-4dd4-aa9d-8ff0593a988d)

我API根据自己的实际情况填写的 https://example.com/upload?authCode=123456
可是picgo上传图片失败，不知道为什么。
![image](https://github.com/user-attachments/assets/a2c16e34-5eb1-4714-841c-39549d3192b7)

**Comment by soslane** [comment]
检查过了，拼写没错误啊发自我的 iPhone在 2024年8月29日，09:54，youngestdriver ***@***.***> 写道：﻿
是不是符号不规范？比如英文状态还是中文状态

**Comment by MarSeventh** [comment]
picgo配置能截图看看吗

**Comment by soslane** [comment]
![image](https://github.com/user-attachments/assets/756e9931-b1a5-487b-950f-c266d6c3a1df)

**Comment by soslane** [comment]
> picgo配置能截图看看吗

麻烦帮我看下

**Comment by soslane** [comment]
> 怎么看起来不像这位作者的项目

我换了背景图片而已啊

**Comment by MarSeventh** [comment]
看报错是请求路径有问题，你试试改成demo站看看能否正常上传？

**Comment by soslane** [comment]
我去掉authcode也是可以上传的

**Comment by MarSeventh** [comment]
要不更新一下picgo吧，感觉是后缀参数有问题。。。

**Comment by soslane** [comment]
好吧，那我删掉这个issue了

**Comment by xiaochenhh** [comment]
不知道为啥这个图片上传失败，其他图片都可以🧐

**Comment by xiaochenhh** [comment]
> > https://tgtc.776676.xyz/file/AgACAgUAAyEGAASHrbjGAAMPZuBCBdZTNpHXwvnVFr-s4pHFjfEAAsvCMRugoQABV4p-42vIqskqAQADAgADdwADNgQ.jpg显示这样，其他图都正常上传
> 
> 您打开了防护热链接，看文档问答。 ![图像](https://private-user-images.githubusercontent.com/108160987/366053822-10338d15-82d7-45b4-85a3-a7ce711e37a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMjA4MzYsIm5iZiI6MTcyNjAyMDUzNiwicGF0aCI6Ii8xMDgxNjA5ODcvMzY2MDUzODIyLTEwMzM4ZDE1LTgyZDctNDViNC04NWEzLWE3Y2U3MTFlMzdhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQwMjA4NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NGFiZjUyMDYzMjM5NTJlN2MzM2JkYTgxY2ViMzBmYzAwYzVjZTMyN2EzMjlmMGM0MmE3NDk5MWJiMjdlMzE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4lUlnhKtpbz_d2fnNcFiFdTwXXKhdFs7BeUcCvbON8c)

已经好了感谢

**Comment by CrazySir** [comment]
> ![image](https://private-user-images.githubusercontent.com/149466045/362501199-f2b13a23-b192-4dd4-aa9d-8ff0593a988d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4MjgzNzgsIm5iZiI6MTczNTgyODA3OCwicGF0aCI6Ii8xNDk0NjYwNDUvMzYyNTAxMTk5LWYyYjEzYTIzLWIxOTItNGRkNC1hYTlkLThmZjA1OTNhOTg4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMlQxNDI3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjVhNzUyNmQ0MDNjN2RiMzllOWRkNzE3NWM3MDJlZjRlMTIxZTU0ZGQ0YjM1OTI5M2E1ODQ2ZjdiZWJlNTFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kx3O_1Jq5hVTA57Pp3lv3pGcSHXH8XnglnlOqHVNEfY)
> 
> 我API根据自己的实际情况填写的 https://example.com/upload?authCode=123456 可是picgo上传图片失败，不知道为什么。 ![image](https://private-user-images.githubusercontent.com/149466045/362502495-a2c16e34-5eb1-4714-841c-39549d3192b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4MjgzNzgsIm5iZiI6MTczNTgyODA3OCwicGF0aCI6Ii8xNDk0NjYwNDUvMzYyNTAyNDk1LWEyYzE2ZTM0LTVlYjEtNDcxNC04NDFjLTM5NTQ5ZDMxOTJiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMlQxNDI3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZThiMzU1OWFlZGY2NDdmYmJjNTM4NTNhMmEyMzc4ODI2NzJhOGFkMjhiOTcxY2Y2Yjg1N2Q4YzM0M2FlYjMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RUJFo0zoxaEWruSoAk1H-FNDQFN1gM8dd10a8irIVKQ)
楼主这个问题我也遇到了，偶尔一两次会上传成功，后来我排查了一下，是环境变量那里设置密文导致的，我把AUTH_CODE改明文不行，全部改明文就可以了，知识现在遇到的问题是picgo不加载图片，全部显示问号文件，这点还没研究明白是什么原因

**Comment by MarSeventh** [comment]
> > ![image](https://private-user-images.githubusercontent.com/149466045/362501199-f2b13a23-b192-4dd4-aa9d-8ff0593a988d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4MjgzNzgsIm5iZiI6MTczNTgyODA3OCwicGF0aCI6Ii8xNDk0NjYwNDUvMzYyNTAxMTk5LWYyYjEzYTIzLWIxOTItNGRkNC1hYTlkLThmZjA1OTNhOTg4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMlQxNDI3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjVhNzUyNmQ0MDNjN2RiMzllOWRkNzE3NWM3MDJlZjRlMTIxZTU0ZGQ0YjM1OTI5M2E1ODQ2ZjdiZWJlNTFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kx3O_1Jq5hVTA57Pp3lv3pGcSHXH8XnglnlOqHVNEfY)
> > 我API根据自己的实际情况填写的 https://example.com/upload?authCode=123456 可是picgo上传图片失败，不知道为什么。 ![image](https://private-user-images.githubusercontent.com/149466045/362502495-a2c16e34-5eb1-4714-841c-39549d3192b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4MjgzNzgsIm5iZiI6MTczNTgyODA3OCwicGF0aCI6Ii8xNDk0NjYwNDUvMzYyNTAyNDk1LWEyYzE2ZTM0LTVlYjEtNDcxNC04NDFjLTM5NTQ5ZDMxOTJiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMlQxNDI3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZThiMzU1OWFlZGY2NDdmYmJjNTM4NTNhMmEyMzc4ODI2NzJhOGFkMjhiOTcxY2Y2Yjg1N2Q4YzM0M2FlYjMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RUJFo0zoxaEWruSoAk1H-FNDQFN1gM8dd10a8irIVKQ)
> > 楼主这个问题我也遇到了，偶尔一两次会上传成功，后来我排查了一下，是环境变量那里设置密文导致的，我把AUTH_CODE改明文不行，全部改明文就可以了，知识现在遇到的问题是picgo不加载图片，全部显示问号文件，这点还没研究明白是什么原因

看看文件命名之类的是不是标准

**Comment by CrazySir** [comment]
![image](https://github.com/user-attachments/assets/cd7a3f41-248f-4e4c-939b-a85888f9e966)

我的设置是这样的，软件神经的很，一会能用一会不能用，现在又不能上传了，所以得撤回之前说的密文问题。

其实我刚搭建好的时候就是picgo设置不好，一直用的网页上传，今天又来了兴头鼓捣了一下，本以为好了，结果.....哈哈哈

**Comment by MarSeventh** [comment]
> ![image](https://private-user-images.githubusercontent.com/71536813/399735189-cd7a3f41-248f-4e4c-939b-a85888f9e966.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4MzE3NTIsIm5iZiI6MTczNTgzMTQ1MiwicGF0aCI6Ii83MTUzNjgxMy8zOTk3MzUxODktY2Q3YTNmNDEtMjQ4Zi00ZTRjLTkzOWItYTg1ODg4ZjllOTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAyVDE1MjQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzYjM4YjA4ZjUwMzViMzI5NWRlNDRmOWE0YmY5NGRmNzc1NThjZmU5YWNhZjZhYzkxNGJmYzdlOWNkNTQzN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0V-oQBIIOWpE29O_OX2Q8RwirG5Zg2H-0FzHcfkSRVM)
> 
> 我的设置是这样的，软件神经的很，一会能用一会不能用，现在又不能上传了，所以得撤回之前说的密文问题。
> 
> 其实我刚搭建好的时候就是picgo设置不好，一直用的网页上传，今天又来了兴头鼓捣了一下，本以为好了，结果.....哈哈哈

这里设置只对Web上传生效啊，API你得设置对应的参数，跟面板设置无关

**Comment by MarSeventh** [comment]
但是正常情况下picgo只需要带个认证码的参数就能用，而且一会可以一会不行的话我感觉大概率是网络或者picgo的问题

**Comment by CrazySir** [comment]
我的感觉是 picgo 的问题，我用的（2.4.0），因为 web 端一直可以正常上传，包括批量，几十张偶尔失败一两张，同时传也试过，picgo 失败，web 正常





------------------ 原始邮件 ------------------
发件人: 叁月柒 ***@***.***&gt;
发送时间: 2025年1月2日 23:27
收件人: 907040997 ***@***.***&gt;
主题: Re: [MarSeventh/CloudFlare-ImgBed] Picgo上传失败 (Issue #23)





 
但是正常情况下picgo只需要带个认证码的参数就能用，而且一会可以一会不行的话我感觉大概率是网络或者picgo的问题

**Comment by MarSeventh** [comment]
> 我的感觉是 picgo 的问题，我用的（2.4.0），因为 web 端一直可以正常上传，包括批量，几十张偶尔失败一两张，同时传也试过，picgo 失败，web 正常
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 叁月柒 ***@***.***&gt; 发送时间: 2025年1月2日 23:27 收件人: 907040997 ***@***.***&gt; 主题: Re: [MarSeventh/CloudFlare-ImgBed] Picgo上传失败 (Issue #23) 但是正常情况下picgo只需要带个认证码的参数就能用，而且一会可以一会不行的话我感觉大概率是网络或者picgo的问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

web端我对并发做了处理的，如果单纯批量调用上传API肯定会有很多失败情况
