### ISSUE TITLE
佬，背景图片不同窗口大小的显示方案可以优化吗(*•ᴗ•)و ̑̑✧

### ISSUE THREAD

**Issue by sorrow233** [MarSeventh/CloudFlare-ImgBed#24]
问题描述：弄好的图片不同屏幕尺寸会被生硬的拉伸，比如不同大小的窗口，不同的设备，看到的都不同

> PC显示：![PC.png](https://pic.k-on.live/file/c7dd5832e55f6929862f0.jpg)

> 手机显示：![Phone.png](https://pic.k-on.live/file/8c1c241f0101ca6773505.png)

需求：能否增加根据设备大小自动裁切。比如手机端只显示屏幕大小的图片内容，而不是生硬的全部显示
测试网站：pic.catzz.work。令牌：catzz

**Comment by MarSeventh** [comment]
可以哈，后面调整

**Comment by MarSeventh** [comment]
已调整

**Comment by sorrow233** [comment]
> 已调整

大佬这效率woww，这就去配置
