### ISSUE TITLE
不知道是tg还是cf封了，已经无法上传了

### ISSUE THREAD

**Issue by sucooer** [MarSeventh/CloudFlare-ImgBed#26]
我以为是自己站点的问题，结果好几个这类站点都应无法上传了，GG

**Comment by MarSeventh** [comment]
官网现在只支持图片链接了，可能需要考虑更换上传渠道

**Comment by CYY118** [comment]
下午那会儿还能上传 现在上传不了了

**Comment by MarSeventh** [comment]
> 下午那会儿还能上传 现在上传不了了

是的，不知道是不是官方有意为之，现在官方匿名博客的图片也只能用外链了。
之前上传的图片应该不会被波及，因为telegram应该会保证之前的匿名博客永久可访问。
先观望一段时间，如果是故意为之，就只能换其他接口上传图片了。

**Comment by sorrow233** [comment]
同，自从电报ceo被抓之后，tg一连串的操作很离谱

**Comment by MarSeventh** [comment]
> 同，自从电报ceo被抓之后，tg一连串的操作很离谱

可能有人用这个图床传播一些敏感内容。。🥲
下一步还是迁移到tg的频道上传吧。

**Comment by nlxxtw** [comment]
传不了，嘎了吗

**Comment by MarSeventh** [comment]
已完成迁移，请看最新文档，设置`TG_BOT_TOKEN`和`TG_CHAT_ID`。
