### ISSUE TITLE
图片上传太多显示不全怎么整

### ISSUE THREAD

**Issue by wunskzb** [MarSeventh/CloudFlare-ImgBed#28]
上传了1000+一共就显示67页全是以前上传的老照片

**Comment by MarSeventh** [comment]
一次上传1000+？？？

**Comment by wunskzb** [comment]
以前上传的，现在上传图片后台看不到最新上传的图片链接

**Comment by MarSeventh** [comment]
最新版吗？我这里没问题呀。

**Comment by MarSeventh** [comment]
演示视频：
https://demo-cloudflare-imgbed.pages.dev/file/BAACAgUAAyEGAASI6XYGAANLZtxX02Kq3A3qUBspwsfVd1NX3H4AAhwTAAIdTuBW8pXEyerFf442BA

**Comment by wunskzb** [comment]
你TG能发给我吗
我把域名和后台密码发给你

**Comment by MarSeventh** [comment]
https://space.bilibili.com/440758033

**Comment by wunskzb** [comment]
发你了
