### ISSUE TITLE
11111111111.jpg上传失败

### ISSUE THREAD

**Issue by hhtnFxQVwQntBLkULKjy** [MarSeventh/CloudFlare-ImgBed#31]
11111111111.jpg上传失败

[图片](https://konachan.net/image/c5341dd074a4d496a1fa17cdef47ee44/Konachan.com%20-%20380728%20apron%20blush%20braids%20breasts%20choker%20cleavage%20collar%20crown%20doll%20dress%20gloves%20group%20hat%20headband%20hug%20maid%20phone%20pink_eyes%20red_eyes%20skirt%20wink%20wristwear.jpg)

**Comment by hhtnFxQVwQntBLkULKjy** [comment]
试一试，反正我上传失败了

**Comment by MarSeventh** [comment]
没问题。
![image](https://github.com/user-attachments/assets/13a67249-b26c-4fcd-8062-1e228359033e)

**Comment by Zxklinux** [comment]
> 没问题。 ![image](https://private-user-images.githubusercontent.com/108160987/365413798-13a67249-b26c-4fcd-8062-1e228359033e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODQ5MTQsIm5iZiI6MTcyNTc4NDYxNCwicGF0aCI6Ii8xMDgxNjA5ODcvMzY1NDEzNzk4LTEzYTY3MjQ5LWIyNmMtNGZjZC04MDYyLTFlMjI4MzU5MDMzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQwODM2NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjE0MTU0YzI1NjcyMTM2M2QwYzkzZjVjZjBlOGNiODRmNzg5MjYxMDQ0M2QzMTU2MjZlMDI2ZmJjNDg5MzMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9ZbtmEbmvbAIDBK6Othd5TuKIEkIK7q-eX4uQIvby6o) 直接复制链接会失败，不清楚问题在哪里。
img.myzest.top 搭建了3天一樣上傳失敗 ，第一天沒問題

**Comment by hhtnFxQVwQntBLkULKjy** [comment]
![屏幕截图 2024-09-08 185808](https://github.com/user-attachments/assets/10b1892f-ca98-40bc-8fca-0cfada4ffad1)
失败

**Comment by MarSeventh** [comment]
新版本优化了大文件的上传稳定性，更新后应该可以正常上传。
