### ISSUE TITLE
切换到tg频道后图片链接不显示格式了

### ISSUE THREAD

**Issue by changeCat** [MarSeventh/CloudFlare-ImgBed#32]
切换到tg后，上传图片，复制的链接是这种格式
https://xxx.kg/file/XXXXXXXXXXXXXXXXXXXXXXXXXXXXM2BA，不像原来的是以.jpg或.png这种了，没原来方便了，这个是因为以tg频道作为存储的原因吗

**Comment by MarSeventh** [comment]
是的，TG存储的ID不包含文件格式

**Comment by changeCat** [comment]
好吧，虽然现在链接没那么美观方便了，还是感谢大佬

**Comment by MarSeventh** [comment]
最新版已经支持显示格式。
