### ISSUE TITLE
图片超过500KB就会自动压缩

### ISSUE THREAD

**Issue by WadeZJT** [MarSeventh/CloudFlare-ImgBed#35]
按照教程一步一步做下来，最终能够成功上传，但是好像只要超过500kb的图片都会被压缩。然后我用readme里的体验地址的那个图床试也是这个情况，不知道是不是telegram的问题

**Comment by MarSeventh** [comment]
是telegarm上传的图都会压缩。

**Comment by WadeZJT** [comment]
您的邮件已收到

**Comment by WadeZJT** [comment]
原来如此，感谢解答
