### ISSUE TITLE
上传失败，同token同chat_id在隔壁X_DR的telegraph-Image可用

### ISSUE THREAD

**Issue by TyroneVeblen** [MarSeventh/CloudFlare-ImgBed#36]
隔壁的是这个https://github.com/x-dr/telegraph-Image。
均使用相同的bot_token和chat_id，环境变量也均只有token和chat_id。
但是此库提示上传失败，x_dr的库则是上传成功。
原因未知

**Comment by wunskzb** [comment]
机器人不能共用，频道可以，再创建一个机器人

**Comment by TyroneVeblen** [comment]
> 机器人不能共用，频道可以，再创建一个机器人

解决了，是作者的文档写的带有一定的误导性，环境变量是TG_BOT_TOKEN和TG_CHAT_ID而不是BOT_TOKEN和CHAT_ID。
