### ISSUE TITLE
新版迁移到telegram之后的BUG，上传遇到的问题

### ISSUE THREAD

**Issue by MicroMatrixOrg** [MarSeventh/CloudFlare-ImgBed#40]
1. 一个17.7MB的视频上传之后，群里出现了这个视频，但是url地址没有显示出来
2. 如果开启了前台验证的话，上传资源就会立即跳到/login页面上

**Comment by MarSeventh** [comment]
1.前台上传是否显示成功？
2.检查密码是否正确，我自用的前台验证没有问题

**Comment by MicroMatrixOrg** [comment]
> 1.前台上传是否显示成功？ 2.检查密码是否正确，我自用的前台验证没有问题

前台上传显示失败，没有出现url地址。
密码是正确的，不然也没法进入到上传页面

**Comment by MarSeventh** [comment]
麻烦提供一下两个问题出现时的截图，方便的话再附上网络接口响应的截图。

**Comment by MicroMatrixOrg** [comment]
![QQ_1725845677919](https://github.com/user-attachments/assets/6a7283ea-1903-49e1-9e17-2c370bf7d622)
第一个问题我找到什么原因了，前台密码中的字符有其他的符号。

**Comment by MicroMatrixOrg** [comment]
第一个问题，在我更换authCode之后也成功了，但是我之前是关闭了authCode进行上传测试的。

**Comment by MarSeventh** [comment]
可能是网络波动，大文件上传不稳定因素较多。

**Comment by lancer-wang** [comment]
这个我也遇到了，tg频道有，但是picgo返回失败，不知道是不是用authCode会稳点
