### ISSUE TITLE
图片上传了显示404

### ISSUE THREAD

**Issue by estds** [MarSeventh/CloudFlare-ImgBed#42]
图片上传成功，TG群里也看到了图片，但是上传界面显示404（如下图）：

<img width="1072" alt="Screenshot 2024-09-09 at 16 48 38" src="https://github.com/user-attachments/assets/05045705-97a4-49be-8459-665ba0a75b99">

打开图片的网址的话，会显示Error 1101
<img width="978" alt="Screenshot 2024-09-09 at 16 48 56" src="https://github.com/user-attachments/assets/15390d67-7919-48b4-ac99-fac6e3f0c0dc">

这个请问要怎么解决？

**Comment by MarSeventh** [comment]
检查KV数据库配置

**Comment by estds** [comment]
> 检查KV数据库配置

嗯 解决了 谢谢
