### ISSUE TITLE
admin页面无限刷新

### ISSUE THREAD

**Issue by rzh0504** [MarSeventh/CloudFlare-ImgBed#46]
如题

**Comment by MarSeventh** [comment]
没法确认问题在哪，该问题极少出现，能否提供更详细信息，如网络请求等。

**Comment by rzh0504** [comment]
> 没法确认问题在哪，该问题极少出现，能否提供更详细信息，如网络请求等。

你看看 https://0286ca83.cloudflare-imgbed-1hj.pages.dev/

**Comment by fsnhljz** [comment]
一样的情况，留空进入以后，右下角进入管理页面，就会出现无限刷新的情况。这种情况是没有添加后台两个变量时会出现。

**Comment by rzh0504** [comment]
> 一样的情况，留空进入以后，右下角进入管理页面，就会出现无限刷新的情况。这种情况是没有添加后台两个变量时会出现。

是username 和 password环境变量这俩么

**Comment by fsnhljz** [comment]
> > 一样的情况，留空进入以后，右下角进入管理页面，就会出现无限刷新的情况。这种情况是没有添加后台两个变量时会出现。
> 
> 是username 和 password环境变量这俩么

项目对应设置->环境变量->为生产环境定义变量->编辑变量 ，添加BASIC_USER作为管理员用户名，BASIC_PASS作为管理员登录密码

**Comment by fsnhljz** [comment]
> 文档里有写： ![image](https://private-user-images.githubusercontent.com/108160987/365700669-d0d3c982-cb35-4dfa-85f3-c707290fbb11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4OTM4MjgsIm5iZiI6MTcyNTg5MzUyOCwicGF0aCI6Ii8xMDgxNjA5ODcvMzY1NzAwNjY5LWQwZDNjOTgyLWNiMzUtNGRmYS04NWYzLWM3MDcyOTBmYmIxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQxNDUyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDc4ZTk0NGJiODkxYzNiZGY1ZTYwZjk2Njk4ZWE1YzM4NTJhZTVjNWU0MTEwNDg5ZmUwZDc3Yzg2NmMzZTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HOUFhFuKaTm7vPPB4i6Y8no0zEpPHJshsi46uXoHpWg)

我理解的关闭应该是点击/admin 这个链接应该是进不去或者提示没有权限，而不是这样无限刷新且显示图片。

**Comment by MarSeventh** [comment]
> > 文档里有写： ![image](https://private-user-images.githubusercontent.com/108160987/365700669-d0d3c982-cb35-4dfa-85f3-c707290fbb11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4OTM4MjgsIm5iZiI6MTcyNTg5MzUyOCwicGF0aCI6Ii8xMDgxNjA5ODcvMzY1NzAwNjY5LWQwZDNjOTgyLWNiMzUtNGRmYS04NWYzLWM3MDcyOTBmYmIxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQxNDUyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDc4ZTk0NGJiODkxYzNiZGY1ZTYwZjk2Njk4ZWE1YzM4NTJhZTVjNWU0MTEwNDg5ZmUwZDc3Yzg2NmMzZTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HOUFhFuKaTm7vPPB4i6Y8no0zEpPHJshsi46uXoHpWg)
> 
> 我理解的关闭应该是点击/admin 这个链接应该是进不去或者提示没有权限，而不是这样无限刷新且显示图片。

这属于原项目遗留问题，我还真没发现过。。。

**Comment by rzh0504** [comment]
> > 文档里有写： ![image](https://private-user-images.githubusercontent.com/108160987/365700669-d0d3c982-cb35-4dfa-85f3-c707290fbb11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4OTM4MjgsIm5iZiI6MTcyNTg5MzUyOCwicGF0aCI6Ii8xMDgxNjA5ODcvMzY1NzAwNjY5LWQwZDNjOTgyLWNiMzUtNGRmYS04NWYzLWM3MDcyOTBmYmIxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQxNDUyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDc4ZTk0NGJiODkxYzNiZGY1ZTYwZjk2Njk4ZWE1YzM4NTJhZTVjNWU0MTEwNDg5ZmUwZDc3Yzg2NmMzZTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HOUFhFuKaTm7vPPB4i6Y8no0zEpPHJshsi46uXoHpWg)
> 
> 我理解的关闭应该是点击/admin 这个链接应该是进不去或者提示没有权限，而不是这样无限刷新且显示图片。

✔️

**Comment by MarSeventh** [comment]
新版本已修复该问题，默认管理端不设密码。

**Comment by sucooer** [comment]
终于解决了😄😄😄
