### ISSUE TITLE
更改背景壁纸轮换时间

### ISSUE THREAD

**Issue by geekqq** [MarSeventh/CloudFlare-ImgBed#50]
修改背景轮换图片源为bing，但是发背景变换的速度很快，请问改那部分的代码可以让它时间拉长一点？
<img width="915" alt="image" src="https://github.com/user-attachments/assets/0612d292-6f75-4e16-b4f5-20cba3d4b45c">
USER_CONFIG
应该不可以直接设置该选项吧？

**Comment by MarSeventh** [comment]
已增加自定义接口，看下最新文档。

**Comment by geekqq** [comment]
<img width="711" alt="image" src="https://github.com/user-attachments/assets/87a20743-f1dc-4497-b230-d73666d0cf1a">

更改了之后似乎没有效果。。请教一下是不是我的语法有问题？

**Comment by MarSeventh** [comment]
需要更新最新版。

**Comment by geekqq** [comment]
哦对啊，sync一下就好了。感谢阁下。速度真是快啊。
