### ISSUE TITLE
建议使用telegram上传文件的API，不要用上传图片的API，图片无论多大都会压缩的。

### ISSUE THREAD

**Issue by Cosmos-Break** [MarSeventh/CloudFlare-ImgBed#51]

**Comment by MarSeventh** [comment]
如果不压缩，加载速度会慢很多，这也是有些人不能接受的。

**Comment by The-GO** [comment]
希望可以把是否需要压缩添加到变量里让用户自己控制打开还是关闭压缩。或者添加个判断，超过多大就自动执行压缩，不超过就不压缩，而不是全部压缩

**Comment by The-GO** [comment]
> 如果不压缩，加载速度会慢很多，这也是有些人不能接受的。

希望可以把是否需要压缩添加到环境变量里让用户自己控制打开还是关闭压缩。或者添加个判断，超过多大就自动执行压缩，不超过就不压缩，而不是全部压缩

**Comment by bian2022** [comment]
> 如果不压缩，加载速度会慢很多，这也是有些人不能接受的。

或许可以在上传界面增加一个接口选项
或者在超过一定大小图片时，询问用户是选择**压缩图片**还是选择**上传原图**
