### ISSUE TITLE
背景图片透明度调整

### ISSUE THREAD

**Issue by geekqq** [MarSeventh/CloudFlare-ImgBed#52]
是否可以增加一个背景图片的透明度自定义？背景看起来太显眼了，有点喧宾夺主了。
https://img.stonehug.com

<img width="1334" alt="image" src="https://github.com/user-attachments/assets/5a8b3e1e-6dde-4bf7-b543-342a4038ddf3">

**Comment by MarSeventh** [comment]
已支持调整透明度，但是由于主底色为白色，显示效果见仁见智。
