### ISSUE TITLE
10几M的图片会上传失败

### ISSUE THREAD

**Issue by WishMelz** [MarSeventh/CloudFlare-ImgBed#56]
10几M的图片会上传失败

**Comment by MarSeventh** [comment]
web还是api，错误提示是什么？

**Comment by MarSeventh** [comment]
web还是api，错误提示是什么？

**Comment by popcion** [comment]
是否是这个问题，但是限制不明
https://github.com/MarSeventh/CloudFlare-ImgBed/issues/45

**Comment by popcion** [comment]
web上传，12MB图片
![image](https://github.com/user-attachments/assets/d059c2b5-40f2-4f5e-9ba0-b995d8b656c6)
![image](https://github.com/user-attachments/assets/100b5069-a139-4677-bc42-a7d9a4bd82d2)

**Comment by popcion** [comment]
经过测试，发现tg分辨率限制和上传图片大小无关。限制如下：
以宽高比5000:5000为基准，宽距离5000有多少个像素，高就反向限制多少个像素，例如：
6000:4000，宽比5000多1000个像素，那么高的最高限制像素为5000-1000=4000像素
上图宽6500，那么高的像素限制为5000-1500=3500，6500:3500是极限。反之，6000:4000是极限。

解决方法可以先计算图片的宽像素距5000有多少，再用5000减去这个数得出的高的上限，与图片的实际高作对比，若实际像素值低于这个值，则不用管，若高于像素值，则以距5000像素值最大的一边(实际就是宽)为基准，令基准为5000像素，加上另一边像素值距5000的差值，得出这边的最终值，保持最终值不变，让原图按照这边的最终值原比例缩放，就能卡上限上传。

例如：
6500:4000，宽距离5000有6500-5000=1500个像素。得到高的上限5000-1500=3500，3500上限与实际高4000对比，4000高于3500上限，不跳过，进行处理：宽6500和高4000，宽距5000值更大，取宽这边5000+|4000-5000|=6000，固定宽为6000进行等比例缩放，最终得出6000:3692，观察到此时高未达4000上限，可以正常上传，缩放比例为93%。固定距离5000较大的一边是因为缩放比会比固定另一边小。若固定另一边，会得到5687:3500，缩放比为88%

6000:3500，宽距离5000有6000-5000=1000个像素。得到高的上限5000-1000=4000，4000上限与实际高3500对比，跳过。

6000:4000，宽距离5000有6000-5000=1000个像素。得到高的上限5000-1000=4000，
4000上限与实际高4000对比，跳过。

**Comment by MarSeventh** [comment]
最新版，上传前可关闭服务端压缩，即可去除像素限制
