### ISSUE TITLE
大佬，现在的这个后台在移动设备上好像有点问题

### ISSUE THREAD

**Issue by 5290x** [MarSeventh/CloudFlare-ImgBed#57]
![Screenshot_20240912_163047_com yujian ResideMenuDemo_edit_331813390495201](https://github.com/user-attachments/assets/9a2d8f95-78aa-4cd5-bc20-957715102d2a)

手机竖屏时展示的图片只有这么一点不方便复制链接，删除等操作，横屏时图片能够显示大部分，但是还是不全

**Comment by MarSeventh** [comment]
别急，已经在做适配了

**Comment by 5290x** [comment]
好的好的，坐等适配

**Comment by MarSeventh** [comment]
麻烦测试一下新版的移动端适配情况，这个版本重构了管理端，有问题欢迎反馈。

**Comment by 5290x** [comment]
哦，好的

**Comment by 5290x** [comment]
嗯，新的后台不错，移动端适配挺好的，就是切换回老后台跟瀑布流的时候得重新再输一次密码跟用户名

**Comment by MarSeventh** [comment]
现在还在beta，后面会完善

**Comment by xiaochenhh** [comment]
> 现在还在beta，后面完善

作者你越做越好了，是学生党嘛😃

**Comment by MarSeventh** [comment]
> > 现在还在beta，后面完善
> 
> 作者你越做越好了，是学生党嘛😃

谢谢❤ 是学生嘞
