### ISSUE TITLE
大佬，管理页面显示的名字可以和真实地址有办法做映射吗

### ISSUE THREAD

**Issue by changeCat** [MarSeventh/CloudFlare-ImgBed#58]
复制的地址是file/后面跟一大串随机字符，这个可以做到和图片下面显示的名称做一个映射吗，就是复制的链接是xxx.com/file/2024-06-08_152423.png，实际后台请求的是真实的路径xxx.com/file/xxxxxxx
![image](https://github.com/user-attachments/assets/79b1863e-4440-46ad-9847-6357bd7ccb80)

**Comment by MarSeventh** [comment]
可以做，就是得想办法兼容现在的格式

**Comment by changeCat** [comment]
> 可以做，就是得想办法兼容现在的格式

兼容现在的格式，是指哪部分

**Comment by MarSeventh** [comment]
看看最新版，完全映射不可能，因为存在冲突，我在文件名前面加了时间戳，应该能最大程度满足需求了。

**Comment by changeCat** [comment]
动作好快，试了下，最新版，新上传的完全没问题，只有已经上传的图片还是原路径，不过已经足够了，感谢大佬

**Comment by MarSeventh** [comment]
已经上传的没法修改了，新上传的会做映射
