### ISSUE TITLE
粘贴模式需点击页面才能上传

### ISSUE THREAD

**Issue by popcion** [MarSeventh/CloudFlare-ImgBed#59]
切换至粘贴模式后需要点击中间的元素才能粘贴上传，无法直接CTRL+V。之后点击旁边的元素再次CTRL+V无反应，再次点击中心元素才能粘贴上传。

**Comment by MarSeventh** [comment]
因为上传框限制在中间。

**Comment by popcion** [comment]
好吧，起因是看其他一些图床是支持整个页面上传。例如以下图床：
https://gateway.ipfsscan.io/ipfs/bafykbzacea267bhwedi3tka2kl6jnln3fbvyj7nsbnzuamteyhz7vk5ezckwa/
https://freeimage.host/
https://img.chkaja.com/
问题在需要每次手动切换，每次切换后点击主页元素，个人认为会增加无意义操作。

**Comment by MarSeventh** [comment]
好的，下个大版本会加上设置记忆功能。

**Comment by popcion** [comment]
非常感谢，顺便请求增加: 点击链接自动复制到剪切板
![image](https://github.com/user-attachments/assets/903e1241-6e03-404d-bfe5-2f61bef4841e)
