### ISSUE TITLE
如何传输普通文件呢?

### ISSUE THREAD

**Issue by ywgx** [MarSeventh/CloudFlare-ImgBed#65]
目前只能选择图片

**Comment by MarSeventh** [comment]
![image](https://github.com/user-attachments/assets/a7918ba2-b2a6-45db-a50b-9053e21236ef)

**Comment by Nothingtodoforma** [comment]
![image](https://github.com/user-attachments/assets/e613e5c4-08be-4d9f-9ed2-17c4d89a0f0b)
选择文件时 先改成所有文件不就可以了
