### ISSUE TITLE
可否去掉前台上传最大20m的限制？

### ISSUE THREAD

**Issue by shanglong2333** [MarSeventh/CloudFlare-ImgBed#69]
可否去掉前台上传最大20m的限制？或者可否告知一下在哪里自己可以修改掉这个限制，个人觉得相对于图片，有这个20m会被压缩的提示就够了，但是前台限制了20m大小后，其他文件或者视频也上传不了超过20m的，比较难受

**Comment by MarSeventh** [comment]
这是因为tg后端的原因，限制文件大小不超过50MB，图片不超过10MB，我之后再研究研究看看怎么最大化上传文件大小。
![image](https://github.com/user-attachments/assets/41ae0f6f-7b9f-4807-954b-8ea8c92525bb)

**Comment by xiaochenhh** [comment]
> 这是因为tg后端的原因，限制文件大小不超过50MB，图片不超过10MB，我之后再研究研究看看怎么最大化上传文件大小。 ![image](https://private-user-images.githubusercontent.com/108160987/370681989-41ae0f6f-7b9f-4807-954b-8ea8c92525bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMTQ5NjMsIm5iZiI6MTcyNzMxNDY2MywicGF0aCI6Ii8xMDgxNjA5ODcvMzcwNjgxOTg5LTQxYWUwZjZmLTdiOWYtNDgwNy05NTRiLThlYThjOTI1MjViYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwMTM3NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YWFlYzAyNTliMTdiMzdhZTljOTRhZGM5Nzk1MDM3ZWM2MDMxZDAxZWRmODQwM2NhZTc3M2E5MDFhZWE5OGMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5ZscTZlsrhGg0dn8xbl7MPaqhidAcgBpOWNB7Q1XTvs)

作者看看这个项目呗
https://github.com/wang-useful/cfblog-plus
能不能搞个这种cfblog😄

**Comment by xiaochenhh** [comment]
> 这是因为tg后端的原因，限制文件大小不超过50MB，图片不超过10MB，我之后再研究研究看看怎么最大化上传文件大小。 ![image](https://private-user-images.githubusercontent.com/108160987/370681989-41ae0f6f-7b9f-4807-954b-8ea8c92525bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMjg4OTAsIm5iZiI6MTcyNzMyODU5MCwicGF0aCI6Ii8xMDgxNjA5ODcvMzcwNjgxOTg5LTQxYWUwZjZmLTdiOWYtNDgwNy05NTRiLThlYThjOTI1MjViYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwNTI5NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzY1N2M0ODc4M2IzMjQwOTVmNDBmZGE4NGUyZTAwY2IyMDgzOWZlY2YxNDBiZmM2MjFkOTY0NzI2MjEzODdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Rm83p5nvrohJg5ePijxwGmVaVyXQk2azHJx7D0Xg-vQ)

这个项目可以上传超过20M的（好像是搞分卷这种）
https://github.com/csznet/tgState

**Comment by MarSeventh** [comment]
暂时不打算搞分片，下一步先把文件上限放到50MB，图片放到20MB（前端自定义压缩阈值，压缩后如果大于10MB，后端自动用文件方式上传；否则根据用户自己意愿，选择用文件或图片方式上传，图片方式上传会在TG端再压缩一次）
