### ISSUE TITLE
设置环境变量后也上传失败

### ISSUE THREAD

**Issue by yikus-tjq** [MarSeventh/CloudFlare-ImgBed#70]
设置也报错，但我设置后台账号密码生效了
![image](https://github.com/user-attachments/assets/21b7900b-6b9b-4729-9ad3-944871d9e28b)
![image](https://github.com/user-attachments/assets/ea4d12f4-3243-4370-9641-e026d3824671)
![image](https://github.com/user-attachments/assets/fa07930d-c709-4c66-aad7-4dcc389a89db)

**Comment by piersonpan** [comment]
我也是上传失败。。。烦

**Comment by MarSeventh** [comment]
> 设置也报错，但我设置后台账号密码生效了 ![image](https://private-user-images.githubusercontent.com/38431925/370976647-21b7900b-6b9b-4729-9ad3-944871d9e28b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MjM1MzksIm5iZiI6MTcyOTQyMzIzOSwicGF0aCI6Ii8zODQzMTkyNS8zNzA5NzY2NDctMjFiNzkwMGItNmI5Yi00NzI5LTlhZDMtOTQ0ODcxZDllMjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDExMjAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ZmQ3NjlhMWRlZWNlYmE4MzcyMjMzYWI0YTIzYmE2NDA2ODVkNzQ2NjAzZDY4MTVhODhjYzE1ZjgzNjljOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zdec_wRJmSArFK_MjnEM7zV6-sXG5RdjufJNP08IKLI) ![image](https://private-user-images.githubusercontent.com/38431925/370976914-ea4d12f4-3243-4370-9641-e026d3824671.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MjM1MzksIm5iZiI6MTcyOTQyMzIzOSwicGF0aCI6Ii8zODQzMTkyNS8zNzA5NzY5MTQtZWE0ZDEyZjQtMzI0My00MzcwLTk2NDEtZTAyNmQzODI0NjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDExMjAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiNjQwODA2NTVlYTI4NjA4ZmY4YmU2OGYyMmY5ODE0MDU3YjE2ZTFmNzY2YmUyNmJmYTE4MTA0Yzk0YjMzNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CqFFa9vjtu3NQr3MTup18wMHCE4VVMrs3flpGa3NwMY) ![image](https://private-user-images.githubusercontent.com/38431925/370977092-fa07930d-c709-4c66-aad7-4dcc389a89db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MjM1MzksIm5iZiI6MTcyOTQyMzIzOSwicGF0aCI6Ii8zODQzMTkyNS8zNzA5NzcwOTItZmEwNzkzMGQtYzcwOS00YzY2LWFhZDctNGRjYzM4OWE4OWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDExMjAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlOTdhYzA1MTZlZGU0M2RlNjJjZWJkZGIzYzU4MzIzNDNkYzNhNzY1OGVjYmQ1ZWM0MTVkMGM4NGU1MTNiNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.24Ev0l573sUPY5IzTUQOA1om6TmLW1h9232vzt6FU14)

这个问题应该出在TG端，检查机器人权限等有没有问题。

**Comment by yikus-tjq** [comment]
> > 设置也报错，但我设置后台账号密码生效了<img alt="图像" width="54.145835876464844" height="21" src="https://private-user-images.githubusercontent.com/38431925/370976647-21b7900b-6b9b-4729-9ad3-944871d9e28b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MjM1MzksIm5iZiI6MTcyOTQyMzIzOSwicGF0aCI6Ii8zODQzMTkyNS8zNzA5NzY2NDctMjFiNzkwMGItNmI5Yi00NzI5LTlhZDMtOTQ0ODcxZDllMjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDExMjAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ZmQ3NjlhMWRlZWNlYmE4MzcyMjMzYWI0YTIzYmE2NDA2ODVkNzQ2NjAzZDY4MTVhODhjYzE1ZjgzNjljOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zdec_wRJmSArFK_MjnEM7zV6-sXG5RdjufJNP08IKLI"> <img alt="图像" width="54.145835876464844" height="21" src="https://private-user-images.githubusercontent.com/38431925/370976914-ea4d12f4-3243-4370-9641-e026d3824671.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MjM1MzksIm5iZiI6MTcyOTQyMzIzOSwicGF0aCI6Ii8zODQzMTkyNS8zNzA5NzY5MTQtZWE0ZDEyZjQtMzI0My00MzcwLTk2NDEtZTAyNmQzODI0NjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDExMjAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiNjQwODA2NTVlYTI4NjA4ZmY4YmU2OGYyMmY5ODE0MDU3YjE2ZTFmNzY2YmUyNmJmYTE4MTA0Yzk0YjMzNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CqFFa9vjtu3NQr3MTup18wMHCE4VVMrs3flpGa3NwMY"> <img alt="图像" width="54.145835876464844" height="21" src="https://private-user-images.githubusercontent.com/38431925/370977092-fa07930d-c709-4c66-aad7-4dcc389a89db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MjM1MzksIm5iZiI6MTcyOTQyMzIzOSwicGF0aCI6Ii8zODQzMTkyNS8zNzA5NzcwOTItZmEwNzkzMGQtYzcwOS00YzY2LWFhZDctNGRjYzM4OWE4OWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDExMjAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlOTdhYzA1MTZlZGU0M2RlNjJjZWJkZGIzYzU4MzIzNDNkYzNhNzY1OGVjYmQ1ZWM0MTVkMGM4NGU1MTNiNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.24Ev0l573sUPY5IzTUQOA1om6TmLW1h9232vzt6FU14">
> 
> 这个问题应该出在TG端，检查机器人权限等有没有问题。

怎么检查？ 可以截图给我们看嘛？ 我机器人已是 订阅里的管理了

**Comment by yikus-tjq** [comment]
> > > 设置也报错，但我设置后台账号密码生效了<img alt="图像" width="54.145835876464844" height="21" src="https://private-user-images.githubusercontent.com/38431925/370976647-21b7900b-6b9b-4729-9ad3-944871d9e28b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MjM1MzksIm5iZiI6MTcyOTQyMzIzOSwicGF0aCI6Ii8zODQzMTkyNS8zNzA5NzY2NDctMjFiNzkwMGItNmI5Yi00NzI5LTlhZDMtOTQ0ODcxZDllMjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDExMjAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ZmQ3NjlhMWRlZWNlYmE4MzcyMjMzYWI0YTIzYmE2NDA2ODVkNzQ2NjAzZDY4MTVhODhjYzE1ZjgzNjljOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zdec_wRJmSArFK_MjnEM7zV6-sXG5RdjufJNP08IKLI"> <img alt="图像" width="54.145835876464844" height="21" src="https://private-user-images.githubusercontent.com/38431925/370976914-ea4d12f4-3243-4370-9641-e026d3824671.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MjM1MzksIm5iZiI6MTcyOTQyMzIzOSwicGF0aCI6Ii8zODQzMTkyNS8zNzA5NzY5MTQtZWE0ZDEyZjQtMzI0My00MzcwLTk2NDEtZTAyNmQzODI0NjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDExMjAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiNjQwODA2NTVlYTI4NjA4ZmY4YmU2OGYyMmY5ODE0MDU3YjE2ZTFmNzY2YmUyNmJmYTE4MTA0Yzk0YjMzNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CqFFa9vjtu3NQr3MTup18wMHCE4VVMrs3flpGa3NwMY"> <img alt="图像" width="54.145835876464844" height="21" src="https://private-user-images.githubusercontent.com/38431925/370977092-fa07930d-c709-4c66-aad7-4dcc389a89db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MjM1MzksIm5iZiI6MTcyOTQyMzIzOSwicGF0aCI6Ii8zODQzMTkyNS8zNzA5NzcwOTItZmEwNzkzMGQtYzcwOS00YzY2LWFhZDctNGRjYzM4OWE4OWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDExMjAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlOTdhYzA1MTZlZGU0M2RlNjJjZWJkZGIzYzU4MzIzNDNkYzNhNzY1OGVjYmQ1ZWM0MTVkMGM4NGU1MTNiNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.24Ev0l573sUPY5IzTUQOA1om6TmLW1h9232vzt6FU14">
> > 
> > 
> > 这个问题应该出在TG端，检查机器人权限等有没有问题。
> 
> 怎么检查？ 可以截图给我们看嘛？ 我机器人已是 订阅里的管理了

我知道了 
![image](https://github.com/user-attachments/assets/84fa2802-c23c-47f3-8bd4-4a6323bb6851)
全开启就可以了

**Comment by piersonpan** [comment]
> 我也是上传失败。。。烦

破案了，，我这边的情况是chatid没有加那条小横线，加了之后就正常了。。。
