### ISSUE TITLE
可不可以设置上传的图片名称与后台的图片名称一致呢？

### ISSUE THREAD

**Issue by pt-fun** [MarSeventh/CloudFlare-ImgBed#79]
可不可以设置上传的图片名称与后台的图片名称一致呢？

**Comment by MarSeventh** [comment]
目前就是一致的呀？

**Comment by pt-fun** [comment]
原来是失败了重试了就名称不一致，但是为什么上传一张可以，我再上传就会失败

**Comment by pt-fun** [comment]
picgo设置也是不能上传的

**Comment by MarSeventh** [comment]
> 原来是失败了重试了就名称不一致，但是为什么上传一张可以，我再上传就会失败

上传同样图片不影响的，你可能哪里设置有问题。

**Comment by MarSeventh** [comment]
> picgo设置也是不能上传的

看文档里面的设置，对着图配

**Comment by pt-fun** [comment]
![微信图片_20241005191734](https://github.com/user-attachments/assets/4e4582b4-b497-451a-9b13-6526ee2f3d5e)

**Comment by pt-fun** [comment]
配置是这样的

我后台的两张同样的图片名称不一致
![Uploading 微信截图_20241005191939.png…]()

**Comment by pt-fun** [comment]
![微信截图_20241005191920](https://github.com/user-attachments/assets/7f8fb721-2dbc-4e82-b6fe-2cc4307f8654)

**Comment by MarSeventh** [comment]
> 
> ![微信图片_20241005191734](https://github.com/user-attachments/assets/4e4582b4-b497-451a-9b13-6526ee2f3d5e)
> 
> 

picgo报错是？
你得看默认域名是不是被墙了，还要检查picgo是不是新版。

**Comment by pt-fun** [comment]
![微信截图_20241005192400](https://github.com/user-attachments/assets/e9f4490d-9faa-4168-88a4-45722b19b0cc)

**Comment by MarSeventh** [comment]
> ![微信截图_20241005192400](https://github.com/user-attachments/assets/e9f4490d-9faa-4168-88a4-45722b19b0cc)
> 

这应该是被墙了

**Comment by pt-fun** [comment]
能解决吗

**Comment by MarSeventh** [comment]
> ![微信截图_20241005191920](https://github.com/user-attachments/assets/7f8fb721-2dbc-4e82-b6fe-2cc4307f8654)
> 

你这上传渠道一样吗？第二个像是从URL里面截取的文件名。

**Comment by MarSeventh** [comment]
> 能解决吗

你换自己域名，或者梯子开tun
