### ISSUE TITLE
访问域名限制能否设置为通配符域名

### ISSUE THREAD

**Issue by lingbaoboy** [MarSeventh/CloudFlare-ImgBed#8]
需要将主域名的所有子域名都加入，一个一个设置太麻烦了

**Comment by hl128k** [comment]
现在的逻辑就是子域名全部都放行的

**Comment by hl128k** [comment]
我添加的就是“域名.xyz”，CloudFlare-ImgBed.域名.xyz就是直接放行的

**Comment by lingbaoboy** [comment]
我添加了环境变量，ALLOWED_DOMAINS，输入了我的3个域名，不知道为啥图片直连能打开，但是在我域名下的网页就打不开

**Comment by lingbaoboy** [comment]
最后我都把这个环境变量删除了重新部署了，不知道为啥还是打不开。
另外请教下这个图片是存储在什么地方的？KV里边我看到只是存储了个链接，貌似没图片的原始文件，所以好奇文件是在哪里存储的？

**Comment by lingbaoboy** [comment]
我重新部署了好几遍，即使不设置任何环境变量，只有在一个相同的主域下可以打开，只要主域不同，即使设置环境变量允许，也打不开图片，返回错误代码是403

**Comment by hl128k** [comment]
调整ALLOWED_DOMAINS之后换浏览器或者用无痕模式试试,图片保存到Telegraph,这边就存一个url,好像是上传之后如果没有查看就不存到kv里面了

**Comment by lingbaoboy** [comment]
是使用的隐身模式，甚至我都重新绑定了个域名进行测试了，但是都是只要夸主域，就不能显示

**Comment by hl128k** [comment]
能给个具体的示例吗

**Comment by hl128k** [comment]
还可以换ip试试

**Comment by MarSeventh** [comment]
我刚才试了下，不设置ALLOWED_DOMAINS的情况下，跨主域没有问题呀。

**Comment by lingbaoboy** [comment]
https://bai.lbb.im/
https://bai.runxi.xyz/
这是一个worker绑定了两个域名
背景图片用的是
https://img.lbb.im/file/158aa94270eedb1d7407c.jpg
图床ALLOWED_DOMAINS设置的是
lbb.im,runxi.xyz
但是我https://bai.runxi.xyz/就是加载不出图片

**Comment by MarSeventh** [comment]
> https://bai.lbb.im/
> https://bai.runxi.xyz/
> 这是一个worker绑定了两个域名
> 背景图片用的是
> https://img.lbb.im/file/158aa94270eedb1d7407c.jpg
> 图床ALLOWED_DOMAINS设置的是
> lbb.im,runxi.xyz
> 但是我https://bai.runxi.xyz/就是加载不出图片
> 

![Screenshot_20240730_190742_com.huawei.browser.jpg](https://github.com/user-attachments/assets/c8028330-e9f3-4a31-9ce0-8998e67ad991)
我这里加载出来了😂

**Comment by MarSeventh** [comment]
> 这好尴尬，我电脑试了chrome 、edge，iPhone试了chrome 都不行

是不是网络原因啊

**Comment by lingbaoboy** [comment]
你使用的是安卓的手机浏览器，会不会是国内手机浏览器不遵守规范啊？你用电脑试试，我这边F12一直显示哪个图片是403 Forbidden

**Comment by MarSeventh** [comment]
> 你使用的是安卓的手机浏览器，会不会是国内手机浏览器不遵守规范啊？你用电脑试试，我这边F12一直显示哪个图片是403 Forbidden

你这个edge确实打不开，但是我刚才用自己的试了一下，两个域名都可以访问同一个图床链接，不知道是什么原因。

**Comment by MarSeventh** [comment]
如果没设环境变量都有问题的话建议看看cloudflare对应域名的防火墙，或是部署该站点的服务器配置。

**Comment by hl128k** [comment]
我印象中403应该是会给你返回一个页面而不是没有任何东西的

**Comment by lingbaoboy** [comment]
![image](https://github.com/user-attachments/assets/0bce9013-07c1-42ea-8e53-2b1abf6a1c2c)

**Comment by MarSeventh** [comment]
响应头里的设置了同源策略，所以没法正常访问：
![image](https://github.com/user-attachments/assets/684179cc-704b-4b48-a78f-9ed8b3fdb745)

**Comment by MarSeventh** [comment]
我这边测试了一些如果是没有被允许的域名访问，只会302重定向，不会出现403.
我猜测是cloudflare的安全策略进行了拦截，你看看安全性->事件->防火墙事件有没有日志。

**Comment by lingbaoboy** [comment]
![image](https://github.com/user-attachments/assets/44b14460-0a73-4511-9971-c20456cf0d47)
关键是我没设置同源

**Comment by MarSeventh** [comment]
看下你绑定域名的安全性设置，是不是启动了防攻击或者类似的。

**Comment by lingbaoboy** [comment]
确实是是给拦截了，这防火墙默认开启的？我都不知道有这东西，还要研究怎么关闭
![image](https://github.com/user-attachments/assets/bccfd4a1-b99f-41fc-b134-2f2f259aa03c)

**Comment by MarSeventh** [comment]
这里关一下，应该是你自己开启的：
![image](https://github.com/user-attachments/assets/7660e451-84f3-417b-b210-71f345389781)

**Comment by hl128k** [comment]
https://dash.cloudflare.com/用户id/域名/rules/configuration-rules
规则这里设置的
![Screenshot_20240730_223011_Firefox.jpg](https://github.com/user-attachments/assets/96943fd2-e898-47cd-8c58-f17ced556cf2)

**Comment by hl128k** [comment]
![Screenshot_20240730_223120_Firefox.jpg](https://github.com/user-attachments/assets/8b336aa9-333a-4ae6-9828-c86de82942b1)

**Comment by lingbaoboy** [comment]
谢谢，已经解决了！看来你需要在说明文档中提醒下后来者了

**Comment by lingbaoboy** [comment]
默认应该是关闭的，可能我不知道什么时候给点开了，不过我感觉这个规则防盗链比通过设置环境变量防盗链还简单些，这个设置规则立即生效，通过环境变量修改允许的域名还需要再重新部署以下

**Comment by lyf-top** [comment]
把项目重新cloudflarepages部署,把之前的kv空间删了，重新设置一个空的kv空间，以前的图片还能访问吗？
上传后的图片只能用链接访问，无法快捷复制mkdown
