### ISSUE TITLE
cloud flare变量问题

### ISSUE THREAD

**Issue by ysluoli** [MarSeventh/CloudFlare-ImgBed#82]
![image](https://github.com/user-attachments/assets/e57d0a39-056c-4091-b1d5-969bcf903337)
这个几个变量不生效 是我那里设置错了吗?

**Comment by 5290x** [comment]
填错了，不是这么填的

**Comment by MarSeventh** [comment]
这几个是用json格式填在UserConfig变量里的，看下文档里面的示例

**Comment by ysluoli** [comment]
> 填错了，不是这么填的

![image](https://github.com/user-attachments/assets/50aa0f9a-9183-4003-b5c7-a9a665e1b021)
是这样吗？？ 真的纯小白一点都不懂代码

**Comment by ysluoli** [comment]
> 这几个是用json格式填在USER_CONFIG变量里的，看下文档里面的示例

![image](https://github.com/user-attachments/assets/50aa0f9a-9183-4003-b5c7-a9a665e1b021)
是这样吗？？ 真的纯小白一点都不懂代码

**Comment by MarSeventh** [comment]
> > 这几个是用json格式填在USER_CONFIG变量里的，看下文档里面的示例
> 
> ![image](https://private-user-images.githubusercontent.com/156728360/375916540-50aa0f9a-9183-4003-b5c7-a9a665e1b021.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MDA2OTQsIm5iZiI6MTcyODcwMDM5NCwicGF0aCI6Ii8xNTY3MjgzNjAvMzc1OTE2NTQwLTUwYWEwZjlhLTkxODMtNDAwMy1iNWM3LWE5YTY2NWUxYjAyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwMjMzMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjAyMGJiZjExZDdjNjlhZTUxMmI3ZTM2YzEyZTVhNjcyN2Q4NTFkNTJiZjNhMjMzNGEzNDFhNTYyYWVjZDBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gRDtKXYK4G4mGpjy2SeLNFRsmroWlT2To21RsEFXrpc) 是这样吗？？ 真的纯小白一点都不懂代码

变量名称是`USER_CONFIG`

**Comment by ysluoli** [comment]
> > > 这几个是用json格式填在USER_CONFIG变量里的，看下文档里面的示例
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/156728360/375916540-50aa0f9a-9183-4003-b5c7-a9a665e1b021.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MDA2OTQsIm5iZiI6MTcyODcwMDM5NCwicGF0aCI6Ii8xNTY3MjgzNjAvMzc1OTE2NTQwLTUwYWEwZjlhLTkxODMtNDAwMy1iNWM3LWE5YTY2NWUxYjAyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwMjMzMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjAyMGJiZjExZDdjNjlhZTUxMmI3ZTM2YzEyZTVhNjcyN2Q4NTFkNTJiZjNhMjMzNGEzNDFhNTYyYWVjZDBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gRDtKXYK4G4mGpjy2SeLNFRsmroWlT2To21RsEFXrpc) 是这样吗？？ 真的纯小白一点都不懂代码
> 
> 变量名称是`USER_CONFIG`

感谢 搞定啦~
