### ISSUE TITLE
上传视频大小问题

### ISSUE THREAD

**Issue by iAJue** [MarSeventh/CloudFlare-ImgBed#86]
> 此外，拖拽上传的方式并没有严格限制文件类型，理论上你可以上传任何不超过50MB的文件，但是暂时不会针对图片和视频外的文件进行特殊优化和适配。

不是说可以上传不超过50M的文件吗,为什么我拖动一个40M的视频进去提示文件过大,不能上传?

**Comment by MarSeventh** [comment]
![image](https://github.com/user-attachments/assets/1b850e44-f56a-4f84-abce-15cadecd5199)
因为50MB只能上传不能下载，已经恢复为20MB
