### ISSUE TITLE
希望能支持设置限制上传的文件的格式

### ISSUE THREAD

**Issue by molikai-work** [MarSeventh/CloudFlare-ImgBed#90]
就是说可以自己限制在网站上，上传的文件格式，比如仅限制能上传特定格式的媒体图片。

**Comment by bian2022** [comment]
> 就是说可以自己限制在网站上，上传的文件格式，比如仅限制能上传特定格式的媒体图片。

你可以在cloudflare里设置，**waf拦截**或者**url跳转**都可以实现你的需求 （url跳转你可以设置如果**包含**什么字符，就跳转到某个网页）

**Comment by molikai-work** [comment]
emm那钻研一下cf的规则去
