### ISSUE TITLE
咨询一个问题，picogo上传照片被压缩

### ISSUE THREAD

**Issue by horizon288** [MarSeventh/CloudFlare-ImgBed#91]
web端上面有压缩的设置，全部关闭了。web上传照片没有被压缩，但是用picgo的上传照片，无一例外，都被压缩了。
折腾了半天也不知道怎么处理
![image](https://github.com/user-attachments/assets/e8f399a9-f9e4-4355-a352-c66c7347ffb4)
<img width="569" alt="1729656003364" src="https://github.com/user-attachments/assets/4e02d193-3f5c-466e-9061-d51f09666f36">

**Comment by MarSeventh** [comment]
web端的压缩设置和api端无关，api端关闭服务器压缩的方法是把`serverCompress`参数设为`false`，挂在请求参数中：
![image](https://github.com/user-attachments/assets/e62bfe11-fc15-4c9e-9df6-4c0ca905faf2)

**Comment by horizon288** [comment]
> web端的压缩设置和api端无关，api端关闭服务器压缩的方法是把`serverCompress`参数设为`false`，挂在请求参数中： ![image](https://private-user-images.githubusercontent.com/108160987/379097701-e62bfe11-fc15-4c9e-9df6-4c0ca905faf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTc3OTksIm5iZiI6MTcyOTY1NzQ5OSwicGF0aCI6Ii8xMDgxNjA5ODcvMzc5MDk3NzAxLWU2MmJmZTExLWZjMTUtNGM5ZS05ZGY2LTRjMGNhOTA1ZmFmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QwNDI0NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODQ5ODUyZTFiOTA1NzJjMTJjYWI3YTVhOWExYjkxZDJlZTYzNWQ2NjIxNmQwMDVhZGQxODk2YTUzODRmMzg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.B_iqRI4yC6tBgyut-be2sV_lM67xLzkyX1HD4H0PWQ8)

感谢。。。。我把serverCompress参数设置错了。。。所以一直不行
