### ISSUE TITLE
实测好像无法上传小于20M的MP4视频和图片

### ISSUE THREAD

**Issue by leaflyingl** [MarSeventh/CloudFlare-ImgBed#93]
是视频格式有问题吗？
图片也无法上传成功
在演示图床也无法上传成功

**Comment by MarSeventh** [comment]
可能是文件本身不规范，更换其他文件试试，还不行检查是不是网络问题？

**Comment by leaflyingl** [comment]
> 可能是文件本身不规范，更换其他文件试试，还不行检查是不是网络问题？

今天又试了下，好像又可以了，不知道是不是ip的问题
