### ISSUE TITLE
作者有意支持对象存储或VPS的方式吗

### ISSUE THREAD

**Issue by sorrow233** [MarSeventh/CloudFlare-ImgBed#94]
疑问：因为对使用TG的这种方法感到不安，要是TG改动规则之前的资源不是会全部博客图文无法访问吗？
需求：很喜欢作者的前端设计，想问一下作者有使用这个前端来开发一个支持对象存储和VPS的版本吗？数据掌握在自己手上总是更有安全感
![真的很喜欢的作者的前端](https://pic.k-on.live/file/1730625661562_image.png)

**Comment by MarSeventh** [comment]
后续计划先支持R2存储

**Comment by MarSeventh** [comment]
已支持R2存储

**Comment by sorrow233** [comment]
> 已支持R2存储

太强了，感谢
