### ISSUE TITLE
上传视频文件名问题无法访问

### ISSUE THREAD

**Issue by iAJue** [MarSeventh/CloudFlare-ImgBed#97]
https://demo-cloudflare-imgbed.pages.dev/file/1730899123092_am%E6%96%B0%E6%89%8B%E7%9A%84%E7%AC%AC%E4%B8%89%E4%B8%AA%E8%A7%86%E9%A2%91%E6%B1%82%E5%A4%A7%E4%BD%AC%E8%AF%84%E4%BB%B7%E4%B8%80%E4%B8%8B#%E5%AE%B6%E9%87%8C%E8%B9%B2%E5%90%B8%E8%A1%80%E5%A7%AC%E7%9A%84%E8%8B%A6%E9%97%B7%20#%E6%BC%AB%E5%89%AA%20#%E5%8A%A8%E6%BC%AB%E5%89%AA%E8%BE%91_7409238831918026010.mp4
这种文件名会导致无法访问
文件大小10M左右
显示Error: Image Not Found

**Comment by MarSeventh** [comment]
#在url里面是锚点，文件名中有这个的话浏览器不会把#传递给后端，会直接截断

**Comment by MarSeventh** [comment]
解决方案是把#转义成`%23`，https://demo-cloudflare-imgbed.pages.dev/file/1730899123092_am%E6%96%B0%E6%89%8B%E7%9A%84%E7%AC%AC%E4%B8%89%E4%B8%AA%E8%A7%86%E9%A2%91%E6%B1%82%E5%A4%A7%E4%BD%AC%E8%AF%84%E4%BB%B7%E4%B8%80%E4%B8%8B%23%E5%AE%B6%E9%87%8C%E8%B9%B2%E5%90%B8%E8%A1%80%E5%A7%AC%E7%9A%84%E8%8B%A6%E9%97%B7%20%23%E6%BC%AB%E5%89%AA%20%23%E5%8A%A8%E6%BC%AB%E5%89%AA%E8%BE%91_7409238831918026010.mp4
