### ISSUE TITLE
上传小文件正常，上传超过10M以上的就会出错

### ISSUE THREAD

**Issue by xixi-furry** [MarSeventh/CloudFlare-ImgBed#98]
一些小的3-4M的图片上传是没有问题的，上传超过10M大小的，就会提示：
![image](https://github.com/user-attachments/assets/fe840906-8491-473c-a991-3e89f2be92c9)

不知道是哪里的问题。难道是现在tg渠道10M都不让上传了么？

**Comment by MarSeventh** [comment]
> 一些小的3-4M的图片上传是没有问题的，上传超过10M大小的，就会提示： ![image](https://private-user-images.githubusercontent.com/59167815/384062485-fe840906-8491-473c-a991-3e89f2be92c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMzM3MjksIm5iZiI6MTczMTAzMzQyOSwicGF0aCI6Ii81OTE2NzgxNS8zODQwNjI0ODUtZmU4NDA5MDYtODQ5MS00NzNjLWE5OTEtM2U4OWYyYmU5MmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDAyMzcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYWE5MjY0MWJiZjlmMWZmZGI5ZTUyMDVhMjBlMzRkZTAwNWIwYzg4OTNmYTg2OTk3MDc0MTkwYTM1OWZhNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QPo0GLyyl8PtwtB394GcyMtSV1gGpIpvCqP8GION-qM)
> 
> 不知道是哪里的问题。难道是现在tg渠道10M都不让上传了么？

他那边是挺迷的（跟图片本身分辨率、完整性等都有关），你把服务端压缩关掉试试，一般就能解决了。
这张图十几M就没问题：
https://demo-cloudflare-imgbed.pages.dev/file/1731033418242_%E5%8A%A8%E6%BC%AB%E4%BA%BA%E7%89%A934.jpg

**Comment by MarSeventh** [comment]
> 还有个建议就是，要是上传的图片的文件名，会自动随机就好了，这样也方便某些信息泄露出去啥的x

你可能不了解这个项目的发展经历😂，最开始就是随机的，后来很多人希望能使用原名才衍化成现在的命名方式，后面可能加个参数自己选吧。

**Comment by xixi-furry** [comment]
好的，明白了，感谢大佬辛苦开发！
